#!/bin/bash
### BEGIN INIT INFO
# Provides: yourautostart
# Required-Start: $remote_fs
# Required-Stop: $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Auto Start Test 
# Descrption: This service is used to test auto start service
### END INIT INFO

case "$1" in
    start):
        echo "Stat"
        nohup  /usr/bin/python3  /home/pi/yourpythonprogram.py &
        ;;
    stop):
        echo "Stop"
        #killall singlepic2baiduyun.py
        echo "Usage: service start_tool start|stop"
        exit 1
        ;; 
esac
exit 0
